---
- hosts: app_servers
  tasks:
    - name: clone repo to app_server
      git: 
       repo: https://github.com/oyedeloy/finalproject1_2020.git
       dest: /home/ec2-user/config
       update: yes
      become: true    
    

    - name: build docker image
      docker_image:
        path: /home/ec2-user/config
        name: voting

    - name: build container
      docker_container:
        name: voting_app
        image: voting
        state: started
        restart: yes       
        ports:
          - "80:80"         
        env:
           REDIS_PASSWORD: "admin"
           REDIS: "10.7.2.110"
           REDIS_PORT: "6379"
    
      
