---
- hosts: redis_server
  tasks: 
    - name: Create a data container
      docker_container:
        name: mydata
        image: busybox
        volumes:
           - ./config/redis:/etc/redis
           - ./config/data:/data
        command: [ "redis-server", "/etc/redis/redis.conf" ]
        ports:
        - 6379:6379
        restart: always
